#:schema node_modules/wrangler/config-schema.json

name = "astros-maki"
compatibility_date = "2025-04-09"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist", binding = "ASSETS" }

[observability]
enabled = true