local_backend: true

logo_url: /logo.svg

backend:
  name: github
  branch: main # change this to your branch
  repo: plboilingNL/astros-maki # change this to your repo
  site_domain: makiorganizacja.nl # change this to your domain
  base_url: https://makiorganizacja.nl # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: "public/images"
public_folder: "/images"

i18n:
  structure: "multiple_folders"
  locales: ["en", "nl"]
  default_locale: "en"

collections:
  - name: "posts"
    i18n: true
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    delete: true
    fields:
      - name: "title"
        widget: "string"
        label: "Post Title"
        i18n: true
      - label: "Draft"
        name: "draft"
        widget: "boolean"
        i18n: "duplicate"
      - label: "Author"
        name: "author"
        widget: "string"
        i18n: "duplicate"
      - label: "Tags"
        name: "tags"
        widget: "list"
        i18n: true
      - label: "Image"
        name: "image"
        widget: "object"
        i18n: true
        fields:
          - { label: Source, name: src, widget: image, i18n: "duplicate" }
          - { label: Alt Text, name: alt, widget: string, i18n: true }
      - label: "Snippet"
        name: "snippet"
        widget: "text"
        i18n: true
      - label: "Publish Date"
        name: "publishDate"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm"
        i18n: "duplicate"
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Tutorials", "News", "Reviews", "Frameworks"]
        i18n: "duplicate"
      - name: "body"
        widget: "markdown"
        label: "Post Body"
        i18n: true
